const sampleData = [
  {
    id: 1,
    title: "One Piece",
    dateAdded: "2021-09-30",
    status: "Watching",
    currentEpisode: 950,
    totalEpisodes: 1107,
    platform: "Crunchyroll",
  },
  {
    id: 2,
    title: "Three Body Problem",
    dateAdded: "2024-05-15",
    status: "Plan to Watch",
    currentEpisode: 0,
    totalEpisodes: 8,
    platform: "Netflix",
  },
  {
    id: 3,
    title: "Naruto: Shippuden",
    dateAdded: "2017-05-15",
    status: "Completed",
    currentEpisode: 500,
    totalEpisodes: 500,
    platform: "Hulu",
  },
  {
    id: 4,
    title: "Attack on Titan",
    dateAdded: "2019-03-15",
    status: "Completed",
    currentEpisode: 87,
    totalEpisodes: 87,
    platform: "CrunchyRoll",
  },
  {
    id: 5,
    title: "Demon Slayer",
    dateAdded: "2020-01-12",
    status: "Watching",
    currentEpisode: 22,
    totalEpisodes: 44,
    platform: "Netflix",
  },
  {
    id: 6,
    title: "My Hero Academia",
    dateAdded: "2018-10-01",
    status: "Watching",
    currentEpisode: 123,
    totalEpisodes: 138,
    platform: "Funimation",
  },
  {
    id: 7,
    title: "Jujutsu Kaisen",
    dateAdded: "2021-05-25",
    status: "Completed",
    currentEpisode: 24,
    totalEpisodes: 24,
    platform: "CrunchyRoll",
  },
  {
    id: 8,
    title: "Sword Art Online",
    dateAdded: "2015-07-17",
    status: "Completed",
    currentEpisode: 96,
    totalEpisodes: 96,
    platform: "Netflix",
  },
  {
    id: 9,
    title: "One Punch Man",
    dateAdded: "2016-02-21",
    status: "Completed",
    currentEpisode: 24,
    totalEpisodes: 24,
    platform: "Funimation",
  },
  {
    id: 10,
    title: "Tokyo Revengers",
    dateAdded: "2022-03-18",
    status: "Plan to Watch",
    currentEpisode: 0,
    totalEpisodes: 24,
    platform: "CrunchyRoll",
  },
  {
    id: 11,
    title: "Black Clover",
    dateAdded: "2019-07-20",
    status: "Watching",
    currentEpisode: 170,
    totalEpisodes: 170,
    platform: "Funimation",
  },
  {
    id: 12,
    title: "Hunter x Hunter",
    dateAdded: "2014-11-09",
    status: "Completed",
    currentEpisode: 148,
    totalEpisodes: 148,
    platform: "Netflix",
  },
  {
    id: 13,
    title: "Bleach",
    dateAdded: "2013-05-22",
    status: "Watching",
    currentEpisode: 200,
    totalEpisodes: 366,
    platform: "CrunchyRoll",
  },
  {
    id: 14,
    title: "Death Note",
    dateAdded: "2012-08-13",
    status: "Completed",
    currentEpisode: 37,
    totalEpisodes: 37,
    platform: "Netflix",
  },
  {
    id: 15,
    title: "Fairy Tail",
    dateAdded: "2015-04-05",
    status: "Watching",
    currentEpisode: 200,
    totalEpisodes: 328,
    platform: "Funimation",
  },
  {
    id: 16,
    title: "Haikyuu!!",
    dateAdded: "2017-06-11",
    status: "Completed",
    currentEpisode: 85,
    totalEpisodes: 85,
    platform: "CrunchyRoll",
  },
  {
    id: 17,
    title: "Fullmetal Alchemist: Brotherhood",
    dateAdded: "2013-03-15",
    status: "Completed",
    currentEpisode: 64,
    totalEpisodes: 64,
    platform: "Netflix",
  },
  {
    id: 18,
    title: "Re:Zero - Starting Life in Another World",
    dateAdded: "2018-09-30",
    status: "Watching",
    currentEpisode: 50,
    totalEpisodes: 50,
    platform: "CrunchyRoll",
  },
  {
    id: 19,
    title: "Mob Psycho 100",
    dateAdded: "2020-01-10",
    status: "Completed",
    currentEpisode: 25,
    totalEpisodes: 25,
    platform: "Funimation",
  },
  {
    id: 20,
    title: "Steins;Gate",
    dateAdded: "2014-02-11",
    status: "Completed",
    currentEpisode: 24,
    totalEpisodes: 24,
    platform: "CrunchyRoll",
  },
  {
    id: 21,
    title: "Code Geass: Lelouch of the Rebellion",
    dateAdded: "2011-05-17",
    status: "Completed",
    currentEpisode: 50,
    totalEpisodes: 50,
    platform: "Funimation",
  },
  {
    id: 22,
    title: "The Promised Neverland",
    dateAdded: "2019-12-08",
    status: "Completed",
    currentEpisode: 23,
    totalEpisodes: 23,
    platform: "Netflix",
  },
  {
    id: 23,
    title: "Dr. Stone",
    dateAdded: "2020-06-21",
    status: "Watching",
    currentEpisode: 35,
    totalEpisodes: 35,
    platform: "CrunchyRoll",
  },
  {
    id: 24,
    title: "Vinland Saga",
    dateAdded: "2021-04-30",
    status: "Completed",
    currentEpisode: 24,
    totalEpisodes: 24,
    platform: "Netflix",
  },
  {
    id: 25,
    title: "Noragami",
    dateAdded: "2016-03-12",
    status: "Completed",
    currentEpisode: 25,
    totalEpisodes: 25,
    platform: "Funimation",
  },
  {
    id: 26,
    title: "Assassination Classroom",
    dateAdded: "2018-02-07",
    status: "Completed",
    currentEpisode: 47,
    totalEpisodes: 47,
    platform: "CrunchyRoll",
  },
  {
    id: 27,
    title: "Seven Deadly Sins",
    dateAdded: "2017-05-11",
    status: "Completed",
    currentEpisode: 100,
    totalEpisodes: 100,
    platform: "Netflix",
  },
  {
    id: 28,
    title: "Erased",
    dateAdded: "2019-09-22",
    status: "Completed",
    currentEpisode: 12,
    totalEpisodes: 12,
    platform: "CrunchyRoll",
  },
  {
    id: 29,
    title: "Parasyte: The Maxim",
    dateAdded: "2015-12-31",
    status: "Completed",
    currentEpisode: 24,
    totalEpisodes: 24,
    platform: "Netflix",
  },
  {
    id: 30,
    title: "Yuri on Ice",
    dateAdded: "2017-03-15",
    status: "Completed",
    currentEpisode: 12,
    totalEpisodes: 12,
    platform: "Funimation",
  },
  {
    id: 31,
    title: "Toradora!",
    dateAdded: "2013-11-19",
    status: "Completed",
    currentEpisode: 25,
    totalEpisodes: 25,
    platform: "CrunchyRoll",
  },
  {
    id: 32,
    title: "Your Lie in April",
    dateAdded: "2018-05-07",
    status: "Completed",
    currentEpisode: 22,
    totalEpisodes: 22,
    platform: "Netflix",
  },
  {
    id: 33,
    title: "Made in Abyss",
    dateAdded: "2021-01-13",
    status: "Completed",
    currentEpisode: 13,
    totalEpisodes: 13,
    platform: "CrunchyRoll",
  },
];

module.exports = { sampleData };
