-- Insert sample users
INSERT INTO users (email, password) VALUES ('user1@example.com', 'password1'),
('user2@example.com', 'password2'),
('user3@example.com', 'password3');

-- Insert content
INSERT INTO content (title, platform, user_id) VALUES ('Attack on Titan', 'CrunchyRoll', 1),
('Demon Slayer', 'Netflix', 1),
('My Hero Academia', 'Funimation', 1),
('Jujutsu Kaisen', 'CrunchyRoll', 1),
('Sword Art Online', 'Netflix', 1),
('One Punch Man', 'Funimation', 1),
('Tokyo Revengers', 'CrunchyRoll', 1),
('Black Clover', 'Funimation', 1),
('Hunter x Hunter', 'Netflix', 1),
('Bleach', 'CrunchyRoll', 1),
('Death Note', 'Netflix', 1),
('Fairy Tail', 'Funimation', 1),
('Haikyuu!!', 'CrunchyRoll', 2),
('Fullmetal Alchemist: Brotherhood', 'Netflix', 2),
('Re:Zero - Starting Life in Another World', 'CrunchyRoll', 2),
('Mob Psycho 100', 'Funimation', 2),
('Steins;Gate', 'CrunchyRoll', 2),
('Code Geass: Lelouch of the Rebellion', 'Funimation', 2),
('The Promised Neverland', 'Netflix', 2),
('Dr. Stone', 'CrunchyRoll', 2),
('Vinland Saga', 'Netflix', 2),
('Noragami', 'Funimation', 2),
('Assassination Classroom', 'CrunchyRoll', 3),
('Seven Deadly Sins', 'Netflix', 3),
('Erased', 'CrunchyRoll', 3),
('Parasyte: The Maxim', 'Netflix', 3),
('Yuri on Ice', 'Funimation', 3),
('Toradora!', 'CrunchyRoll', 3),
('Your Lie in April', 'Netflix', 3),
('Made in Abyss', 'CrunchyRoll', 3);